### ISSUE TITLE
tailwind grids

### ISSUE THREAD

**Issue by Terdanny1** [Terdanny1/Bidders-Landing-Page#1]
Trying to fix my grid in order for it to fit in well in both desktop and mobile view
![WhatsApp Image 2022-09-09 at 10 43 17 PM](https://user-images.githubusercontent.com/100247836/189465790-a263dab8-95c9-4e6e-b926-f4dba0c35835.jpeg)

**Comment by Josephenoch** [comment]
#3 would close this issue
